#!/usr/bin/env ruby
# encoding: utf-8


# Do not run this file.  It is for developer testing only.  Use bin/git-topic.

require 'rubygems'

$:.unshift "#{File.dirname(__FILE__)}/lib"
require 'git_topic'
require 'git_topic/cli'

require 'ruby-debug'

GitTopic::run
